<?php

namespace AppBundle\Repository;

use AppBundle\Libs\Normalizer\ResultDecorator;
use AppBundle\Libs\Repository\BaseRepository;
use Doctrine\ORM\EntityRepository;

/**
 * PermitRevisionRepository
 *
 * @author Yosviel Dominguez <yosvield@gmail.com>
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermitRevisionRepository extends BaseRepository {

    public function getBaseQuery($baseEntity, $start = 0, $limit = 30, $filters = array(), $columnsAlias = array(), $decorator = ResultDecorator::DEFAULT_DECORATOR) {

    }

    /**
     * @author Yosviel Dominguez <yosvield@gmail.com>
     * @param $idpermit
     * @return array
     */
    public function getByPermite($idpermit){
        $qb = $this->createQueryBuilder('permit_revision')
            ->innerJoin('permit_revision.permitpermittype', 'permitpermittype')
            ->innerJoin('permitpermittype.permit', 'permit')
            ->andWhere("permit.id = (:idpermit)")
            ->setParameter('idpermit', $idpermit);

        return $qb->getQuery()->getResult();
    }
}
