<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PermitTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermitTypeRepository extends \AppBundle\Libs\Repository\BaseRepository {

    public function getBaseQuery($baseEntity, $start = 0, $limit = 30, $filters = array(), $columnsAlias = array(), $decorator = ResultDecorator::DEFAULT_DECORATOR) {

    }

    /**
     * @author Yosviel Dominguez <yosvield@gmail.com>
     * @param $idpermit
     * @return array
     */
    public function getByPermit($idpermit){
        $qb = $this->createQueryBuilder('permitType')
            ->innerJoin('permitType.permits', 'ppType')
            ->innerJoin('ppType.permit', 'permit')
            ->andWhere("permit.id = (:idpermit)")
            ->setParameter('idpermit', $idpermit);

        return $qb->getQuery()->getResult();
    }
}
