parameters:

services:
 manager.json:
        class: AppBundle\Libs\Normalizer\ManagerNormalizer
        arguments: ["@service_container"]
 app.controller_listener:
        class: AppBundle\Listeners\BeforeControllerListener
        arguments: ["@service_container"]
        tags:
           - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
 exception_listener:
      class: AppBundle\Listeners\ExceptionListener
      arguments: []
      tags:
          - { name: kernel.event_listener, event: kernel.exception, priority: 1 }
 manager.email:
         class: AppBundle\Libs\Helper\SendCustomEmail
         arguments: ["@service_container"]
 manager.validator:
        class: AppBundle\Libs\Validator\ManagerValidator
        arguments: ["@service_container"]
 app.request_listener:
        class: AppBundle\Listeners\RequestListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
 normalizer.role:
        class: AppBundle\Libs\EntityNormalizer\RoleNormalizer
 normalizer.user:
        class: AppBundle\Libs\EntityNormalizer\UserNormalizer
 importfileimage:
        class: AppBundle\Libs\Import\ImportFile
        arguments: [%kernel.root_dir%]
 jwt_token_authenticator:
        class: AppBundle\Controller\JwtTokenAuthenticator
        autowire: true
