parameters:

services:
 manager.json:
        class: AppBundle\Libs\Normalizer\ManagerNormalizer
        arguments: ["@service_container"]
 app.controller_listener:
        class: AppBundle\Listeners\BeforeControllerListener
        arguments: ["@service_container"]
        tags:
           - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
 exception_listener:
      class: AppBundle\Listeners\ExceptionListener
      arguments: []
      tags:
          - { name: kernel.event_listener, event: kernel.exception, priority: 1 }
 manager.email:
         class: AppBundle\Libs\Helper\SendCustomEmail
         arguments: ["@service_container","@twig"]
 manager.validator:
        class: AppBundle\Libs\Validator\ManagerValidator
        arguments: ["@service_container"]
 validator.permituserprofile:
         class: AppBundle\Libs\Validator\PermitUserProfileValidator
 validator.permit:
         class: AppBundle\Libs\Validator\PermitValidator
 validator.location:
         class: AppBundle\Libs\Validator\LocationValidator
 app.request_listener:
        class: AppBundle\Listeners\RequestListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
 normalizer.role:
        class: AppBundle\Libs\EntityNormalizer\RoleNormalizer
 normalizer.company:
        class: AppBundle\Libs\EntityNormalizer\CompanyNormalizer
 normalizer.user:
        class: AppBundle\Libs\EntityNormalizer\UserNormalizer
 normalizer.permit:
        class: AppBundle\Libs\EntityNormalizer\PermitNormalizer
 normalizer.permittype:
        class: AppBundle\Libs\EntityNormalizer\PermitTypeNormalizer
 normalizer.permitimprovementtype:
        class: AppBundle\Libs\EntityNormalizer\PermitImprovementTypeNormalizer
 normalizer.countrystates:
        class: AppBundle\Libs\EntityNormalizer\CountryStatesNormalizer
